// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylqmctvkzeyldjpuhlvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlscW1jdHZremV5bGRqcHVobHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjI4MDUsImV4cCI6MjA2NTgzODgwNX0.UTsGKKpbMf-IJuM0cuPOFNeggpv09lAT4TEbgbCUszM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);